### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by coquizen** [learn-co-curriculum/bonus-setup-readme#4]
For Git Visualizer there is [GitKraken](https://www.gitkraken.com/)
and Window Management, I like using [Amethyst](https://github.com/ianyh/Amethyst) as it is a good tiling window manager (with some glitches, however, when it comes to mouse follows focus).

**Comment by maxwellbenton** [comment]
Hi @CaninoDev,

Thank you for these suggestions. We've updated this lesson and have decided to include your suggestion of GitKraken in the Git visualization section. We did not include Amethyst at this time, but appreciate you taking the time to make these recommendations.

Thank you for contributing to a Learn.co lesson! 💙
