### ISSUE TITLE
404 page when clicking on "More Fonts"

### ISSUE THREAD

**Issue by artismarti** [learn-co-curriculum/bonus-setup-readme#5]
http://www.openwatcom.org/index.php/Programmers_Fonts

When clicking on "More Fonts" under the "Programming Fonts" section the link leads to a 404 page.

![image](https://user-images.githubusercontent.com/111852/45584547-868d1700-b8cd-11e8-92a0-50c87589dbd2.png)

**Comment by maxwellbenton** [comment]
HI @artismarti,

Thank you for spotting this and providing feedback. We've removed this link, updated this lesson's contents and checked the other links provided and believe all links should now be working correctly.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
